### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [AflahB/aflah-bhari-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by AflahB** [comment]
Done :)
Also wow, I didn't expect this theme to get any attention. It was really only for personal use. If there's any issues please let me know and I'll try my best to resolve them.
